language: node_js

node_js:
  - "4.0"

before_install:
  - export TSD_GITHUB_TOKEN=600c7f2cb9a4cd36521d03c24a032ef0aa8e8c47

script:
 - npm run lint
 - npm run typescript

after_success: ./tools/deploy.sh

branches:
  only:
    - master
